name: Deploy to VPS

on:
    push:
        branches: [ prod ]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to VPS
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  port: 22
                  script: |
                      echo "🚀 Début du déploiement en production..."

                      # Vérifier si le dossier symfony existe
                      if [ ! -d "/var/www/production" ]; then
                        echo "📁 Premier déploiement - Création du dossier symfony"
                        sudo chown $USER:$USER /var/www/production
                        cd /var/www/

                        # Clone du repository
                        echo "📥 Clonage du repository..."
                        git clone git@github.com:DBouraoui/symfony-7.3-starter.git production

                        #Déploiement première fois
                        cd /var/www/production

                        make prod-first-time
                      else
                        echo "🔄 Mise à jour du projet existant"
                        cd /var/www/production

                        # Sauvegarder les changements locaux si nécessaire
                        git stash

                        # Pull des dernières modifications
                        echo "📥 Récupération des dernières modifications..."
                        git pull origin prod
                      fi

                      cd /var/www/production

                      # Vérifier si le Makefile existe
                      if [ ! -f "makefile" ]; then
                        echo "❌ Erreur: Makefile non trouvé dans le projet"
                        exit 1
                      fi

                      # Lancer la commande make prod
                      echo "🏗️ Lancement de make prod..."
                      make prod

                      # Vérifier si la commande s'est bien exécutée
                      if [ $? -eq 0 ]; then
                        echo "✅ Déploiement terminé avec succès!"
                      else
                        echo "❌ Erreur lors du make prod"
                        exit 1
                      fi

                      echo "🎉 Déploiement finalisé sur $(date)"

            - name: Notification
              if: always()
              run: |
                  if [ "${{ job.status }}" == "success" ]; then
                    echo "✅ Déploiement réussi sur le VPS"
                  else
                    echo "❌ Échec du déploiement"
                  fi
